### ISSUE TITLE
Arrange date nav and jump controls into one navbar

### ISSUE THREAD

**Issue by jvine** [sul-dlss/library_hours_rails#10]
### Before

![screen shot 2016-09-23 at 2 46 46 pm](https://cloud.githubusercontent.com/assets/6945691/18802300/d9824bc0-819c-11e6-9fd2-035e4efe5d77.png)

### After

![screen shot 2016-09-23 at 2 54 18 pm](https://cloud.githubusercontent.com/assets/6945691/18802445/a437ec26-819d-11e6-82d3-03ba3e3a0a24.png)

- navbar is full container width
- background color $color-beige-10
- border $color-beige-20
- arrows sul-i-arrow-left-3 and sul-i-arrow-right-3
- add sr-only text for "Next" and "Previous" 
- truncate month name to 4 characters
- date range is h2 with size adjusted to 1.2em
- calendar/date picker: prefer the same control used in Requests 
- Quarters & holidays: add SUL btn-default styling (beige instead of grey) (separate ticket for additional Q&H changes)

### Responsive collapse

![screen shot 2016-09-23 at 3 00 58 pm](https://cloud.githubusercontent.com/assets/6945691/18802587/91049266-819e-11e6-81dc-1fc099ba0da4.png)

**Comment by cbeer** [comment]
> truncate month name to 4 characters

Is 3 characters (the rails default) ok?

**Comment by jvine** [comment]
Yes 3 chars is ok

**Comment by cbeer** [comment]
>  prefer the same control used in Requests

I think requests is still using that webshim polyfill that is unsupported and does not work with modern jquery versions. Can I strongly suggest we either keep the browser default behavior, or go looking for a supported shim with the features we want?

**Comment by jvine** [comment]
Browser support for input type=date is inconsistent. If there's no date picker (Firefox, Safari...) we  need to enforce a date format in the UI, because a) the user needs to know what to do, and b) the app throws an error if you get it wrong. So a shim seems useful. Goals are accessibility, error prevention, and consistency across our products. I don't think browser default behaviour gets us there. If someone knows of something better than Requests is using, that's great; we're going to be working on Requests soon too.
