### ISSUE TITLE
Quarters & holidays dropdown

### ISSUE THREAD

**Issue by jvine** [sul-dlss/library_hours_rails#11]
Change button text to "Quarters & holidays"

List structure:

- add `<h3 class="sr-only">Jump to quarters & holidays</h3>` hidden heading at top of list
- make the unlinked years `<h4>` and indent them to match the other list items
- add separators between the years 

Revert to default styling for the button and dropdown:

- remove height/width/overflow styling from the dropdown
- remove width styling from the button
- remove font-sizing from both

![screen shot 2016-09-23 at 11 03 21 am](https://cloud.githubusercontent.com/assets/6945691/18802631/d491d3ae-819e-11e6-810f-4e388fbbc6c8.png)

**Comment by cbeer** [comment]
> add <h3 class="sr-only">Jump to quarters & holidays</h3> hidden heading at top of list

Where? In the dropdown itself?

**Comment by jvine** [comment]
Immediately before the `<button id="jump-term" ...`
