### ISSUE TITLE
Date pagination arrows don't work on mobile

### ISSUE THREAD

**Issue by jvine** [sul-dlss/library_hours_rails#114]
Reported on Safari on iPhone and verified in Chrome on iPhone. The arrows that navigate to the next / previous week are non-functional. Seems to be a z-index issue - the div that contains the jump-to control and Quarters & holidays dropdown covers the date-pagination div on mobile - something to do with the .sr-only class absolute positioning. I think. 

In any case, sticking a high z-index on nav.date-pagination seems to fix it.

**Comment by cbeer** [comment]
How high is high?

**Comment by cbeer** [comment]
Never mind; the real problem is the typo in `col-xs-12` in the control div.
