### ISSUE TITLE
Heading structure & styling

### ISSUE THREAD

**Issue by jvine** [sul-dlss/library_hours_rails#13]
### h1: Library hours or Library name or Location name, depending on context.
![screen shot 2016-09-23 at 3 33 39 pm](https://cloud.githubusercontent.com/assets/6945691/18803242/2d0ea9ae-81a3-11e6-945b-d4c0644a0760.png)

### h2: Date range 
![screen shot 2016-09-23 at 3 34 56 pm](https://cloud.githubusercontent.com/assets/6945691/18803258/4f731958-81a3-11e6-927e-fa3a94438792.png)

### h3: Library names (on home page)
![screen shot 2016-09-23 at 3 35 13 pm](https://cloud.githubusercontent.com/assets/6945691/18803263/5ba99fc6-81a3-11e6-9a5c-360df70c81ef.png)

### css

```
h1 {font-size: 2.986em; font-weight: 100; letter-spacing: 0;}
   @media (max-width: 767px) {
	h1 {font-size:  2.488em;}
	}
h2 {font-size: 2.074em; font-weight: 100;}
h3 {font-size: 1.728em; font-weight: 100;}
h4 {font-size: 1.2em; font-weight: 400;}
```

**Comment by cbeer** [comment]
Fixed by #17
