### ISSUE TITLE
New location doesn't have "node" field

### ISSUE THREAD

**Issue by jvine** [sul-dlss/library_hours_rails#165]
Is this a bug, or did something change? Creating a new library for Redwood City (https://library-hours.stanford.edu/libraries/29) with a location that has hours (https://library-hours.stanford.edu/libraries/29/locations/lobby-desk). The location doesn't have a node field, so there's no way to link it to its page on the website. Location node is 166410.

**Comment by cbeer** [comment]
I've added it behind the scenes. Seems like we might not render field unless there's already data?

**Comment by jvine** [comment]
Weird. But thanks, it's working.

**Comment by cbeer** [comment]
I was going to reopen the bug so we could track this... but, it's already been reported 3 years ago: #6
