### ISSUE TITLE
Location & access link missing for Library; extraneous Hours heading on Location

### ISSUE THREAD

**Issue by jvine** [sul-dlss/library_hours_rails#18]
See #14 

Library should have a link to its node ref, missing here:
![screen shot 2016-09-26 at 1 31 14 pm](https://cloud.githubusercontent.com/assets/6945691/18850707/8b1e8496-83ed-11e6-842d-f99a8ace1807.png)

Location has an extra "Hours" h2 heading that should be removed:
![screen shot 2016-09-26 at 1 31 43 pm](https://cloud.githubusercontent.com/assets/6945691/18850835/21f7ec9a-83ee-11e6-83d7-a611179b16f3.png)

**Comment by cbeer** [comment]
Fixed in ca8e72b36540ba76ce334845eb745573ef6ca23d.
