### ISSUE TITLE
Unable to login to Hours

### ISSUE THREAD

**Issue by jvine** [sul-dlss/library_hours_rails#210]
Not logged in, link shows as  `: Logout`

Click the link and it says I have been successfully logged out - which is true I guess? but login never happened. Still shows as  `: Logout`

 . <img width="600" alt="Screen Shot 2020-04-01 at 5 14 17 PM" src="https://user-images.githubusercontent.com/6945691/78198063-47d19a00-743c-11ea-9bed-ceaf0d66126d.png">

New hours updates are imminent...

**Comment by mejackreed** [comment]
@jvine the fix was deployed out around 2020-04-01 ~ 6:30 PM PT
