### ISSUE TITLE
hide locations not accessible to patrons

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/library_hours_rails#311]
SAL operations hours are currently displayed

**Comment by saseestone** [comment]
We need to add a mechanism for staff logged into library-hours to "Remove Library from view".  Doing so, would suppress the entire Library block from view in https://library-hours.stanford.edu/.

If we remove the library block from display, this will also effect the display for staff logged in, and managing the hours display.  We can live with documenting outside the application that staff will they need to edit the url to get to the correct edit page (e.g. https://library-hours.stanford.edu/libraries/sal/edit) Better would be some way to display only to staff logged in, with a link to manage the Library.
