### ISSUE TITLE
reCAPTCHA issue in feedback

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/library_hours_rails#390]
We're getting an error message in the feedback. Looks like we're missing a site key.

![image](https://user-images.githubusercontent.com/14897546/192006443-28d0e995-2aab-4195-ba64-5fb35d61ca2c.png)

**Comment by thatbudakguy** [comment]
looks like it should be set:
https://github.com/sul-dlss/library_hours_rails/blob/83392b004cc0b62dfe5c14e89581f7bd83cfd67b/config/settings.yml#L8

i'll see if it's indeed set in production.

**Comment by thatbudakguy** [comment]
ahh, I forgot...that key value is a placeholder; the AAAAA and yyyyyy bits are supposed to be filled in by real (secret) values. also, I forgot to set the real ones 8 months ago when we enabled the captcha. my bad!

**Comment by saseestone** [comment]
wow...8 months.... huh.
