### ISSUE TITLE
Nov. 6 2022 hours incorrect

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/library_hours_rails#392]
We need to correct hours for Nov. 6, 2022 for the following libraries:

Earth Sciences; Library & circulation should be: 12p-6pm
East Asia, Library  circulation should be: 12p-8p
Engineering, Library & circulation should be: 12p-6p
Lathrop Library, Learning Hub should be: 1p-6p

Currently we're displaying both "closed" and the correct hours range for that location on that date. @cbeer has fixed this issue before on the Sunday when daylight savings ends.

**Comment by jcoyne** [comment]
Is this the same as #40?

**Comment by saseestone** [comment]
Niqui and I did some testing on sul-hours-dev. I input hours for Green Library's "Library & circulation" location for Nov 1-4, 2024. The display looks fine.  Niqui confirmed the API also looked ok.

We're going to close this ticket (and put a reminder on my calendar to check the hours in October 2024.)

Here' are some screengrabs from this round of testing:

From staff login screen:
<img width="515" alt="image" src="https://github.com/sul-dlss/library_hours_rails/assets/14897546/b432aa9e-f987-4339-afb4-94a2c48f8fa7">


From https://library-hours-dev.stanford.edu/?week=2024W45
<img width="774" alt="image" src="https://github.com/sul-dlss/library_hours_rails/assets/14897546/31371124-0572-4e57-9b7e-3b1e5b63e42c">

**Comment by dnoneill** [comment]
Results from the API:

```
id | 62976
day | "2024-11-02"
weekday | "Saturday"
opens_at | "2024-11-02T08:00:00.000-07:00"
closes_at | "2024-11-02T17:00:00.000-07:00"
type | ""
notes | ""
location_slug | "library-circulation"
location_id | 12
closed | false
```
