### ISSUE TITLE
Add flag to Locations to indicate "primary" Library hours

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/library_hours_rails#440]
To support integration with the new D9 library website, we need to add a method for library hours administrators to indicate that a particular location is the "primary" location for the library/branch. Then we need to expose this flag in the API, so that other applications know which location to use as the "primary" location.

Use case: 
Stanford Web Services (SWS) is creating a "branch card" element that can be added to a Drupal page. The branch card will have: 

- an image of the branch
- contact information for the branch
- One entry line for today's hours - which should correspond to the branch "front door" hours. 

The issue is that we don't have a consistent location label or method within the API to signal to SWS which location to select for that "one entry line for today's hours". By adding a "primary location" flag, hours administrators can select the correct location hours line to be used by other applications.  Then each application doesn't have to hardcode a list of library/location values to use as the "primary" hours entry.

**Comment by saseestone** [comment]
I forgot to add a note about timeline.  SWS is working on the branch card this week. The Tech Lead indicated that if we could have this work done in the next week (Jan 18-Jan 25) that would be ideal. If not possible, before the end of January would be preferred.

**Comment by marlo-longley** [comment]
Hi @saseestone, thanks to @cbeer's work we just merged a solution that will result in the following style json at the [/libraries.json](http://library-hours.stanford.edu/libraries.json) endpoint. Note the `primary_location` value. 
```
{"data"=>
  [{"type"=>"libraries",
    "id"=>"green",
    "attributes"=>
     {"name"=>"Some Library",
      "primary_location"=>"green/some-location",
      "hours"=>
       [{"day"=>"2023-01-15", "weekday"=>"Sunday", "closed"=>true},
        {"day"=>"2023-01-16", "weekday"=>"Monday", "closed"=>true},
        {"day"=>"2023-01-17", "weekday"=>"Tuesday", "closed"=>true},
        {"day"=>"2023-01-18", "weekday"=>"Wednesday", "closed"=>true},
        {"day"=>"2023-01-19", "weekday"=>"Thursday", "opens_at"=>"2023-01-19T00:00:00.000-08:00", "closes_at"=>"2023-01-19T23:59:59.999-08:00", "type"=>"Open", "closed"=>false},
        {"day"=>"2023-01-20", "weekday"=>"Friday", "closed"=>true},
        {"day"=>"2023-01-21", "weekday"=>"Saturday", "closed"=>true}]},
    "relationships"=>{"locations"=>{"data"=>[{"type"=>"locations", "id"=>"green/some-location"}], "links"=>{"related"=>"http://www.example.com/libraries/green/locations"}}},
    "links"=>{"self"=>"http://www.example.com/libraries/green"}}],
 "included"=>
  [{"type"=>"locations",
    "id"=>"green/some-location",
    "attributes"=>
     {"name"=>"Some Location",
      "primary"=>true,
      "hours"=>
       [{"day"=>"2023-01-15", "weekday"=>"Sunday", "closed"=>true},
        {"day"=>"2023-01-16", "weekday"=>"Monday", "closed"=>true},
        {"day"=>"2023-01-17", "weekday"=>"Tuesday", "closed"=>true},
        {"day"=>"2023-01-18", "weekday"=>"Wednesday", "closed"=>true},
        {"day"=>"2023-01-19", "weekday"=>"Thursday", "opens_at"=>"2023-01-19T00:00:00.000-08:00", "closes_at"=>"2023-01-19T23:59:59.999-08:00", "type"=>"Open", "closed"=>false},
        {"day"=>"2023-01-20", "weekday"=>"Friday", "closed"=>true},
        {"day"=>"2023-01-21", "weekday"=>"Saturday", "closed"=>true}]},
    "relationships"=>{"library"=>{"links"=>{"related"=>"http://www.example.com/libraries/green"}, "data"=>{"type"=>"libraries", "id"=>"green"}}},
    "links"=>{"self"=>"http://www.example.com/libraries/green/locations/some-location"}}]}
```

This should go out on Monday with our regular deployments.

**Comment by saseestone** [comment]
Many thanks for the help on this!

**Comment by marlo-longley** [comment]
After this is deployed, someone will have to select the primary locations for each library before any data shows up in the API. @saseestone
