### ISSUE TITLE
Urgent: Can't edit individual day/location hours

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/library_hours_rails#443]
I'm receiving reports from two hours admins (Ellie and Rebecca) that they can't update the hours on a specific date for a specific location. 

I've screen recorded what is happening now, but essentially when the logged in admin clicks on hours entry to update it, you see the modal and can input the new hours, but when you click either the checkbox to save or the x to close, the hours entry for the date just disappears from view.  A refresh of the page displays the original hours that the user is trying to update.

They are trying to update the hours for the David Rumsey Map Center for Wednesday 1/25 to closed.

**Comment by saseestone** [comment]
https://user-images.githubusercontent.com/14897546/214196938-485ca87f-b4ef-4e5b-8f0d-8790ab225d21.mov

**Comment by corylown** [comment]
Fixed by releasing changes in https://github.com/sul-dlss/library_hours_rails/releases/tag/v1.3.0
