### ISSUE TITLE
Hours admins are unable to edit term hours

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/library_hours_rails#484]
The Term Hours section should have similar links to what we see in the specific location view below. Instead it is missing.

![Screenshot 2023-08-02 at 16 37 02](https://github.com/sul-dlss/library_hours_rails/assets/1328900/8bc55e51-951d-4356-acfa-04b52d90e03f)
![Screenshot 2023-08-02 at 16 37 21](https://github.com/sul-dlss/library_hours_rails/assets/1328900/e04388c4-6d29-4114-a485-5d7a59a1c024)
![Screenshot 2023-08-02 at 16 37 50](https://github.com/sul-dlss/library_hours_rails/assets/1328900/3a038e14-b8a6-4338-b4f8-9dc7ac7b9574)

**Comment by marlo-longley** [comment]
@saseestone based on our discussion

**Comment by cbeer** [comment]
It looks like the switch from bootstrap-editable to our own logic in #428 missed this whole workflow?
