### ISSUE TITLE
Drupal slug and node references: Investigate and delete if possible

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/library_hours_rails#485]
We think this is a holdover from D7 but need to investigate.
If possible it would be best to remove these unused form inputs but currently they aren't breaking anything by existing.

This is in the location edit view, e.g. https://library-hours.stanford.edu/libraries/spc/locations/field-reading-room/edit

![Screenshot 2023-08-02 at 16 40 09](https://github.com/sul-dlss/library_hours_rails/assets/1328900/383c0abc-f94d-46ee-ae19-5a4bcc4501bd)

**Comment by marlo-longley** [comment]
@saseestone based on our discussion.

**Comment by cbeer** [comment]
Isn't this https://github.com/sul-dlss/library_hours_rails/issues/478 / https://github.com/sul-dlss/library_hours_rails/pull/481?

**Comment by jcoyne** [comment]
@cbeer yes, this should be fixed by #481
