### ISSUE TITLE
Creating a new library or location should provide fields for the drupal node id

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/library_hours_rails#6]
e.g. as with existing mappings:

![screen shot 2016-03-30 at 3 39 49 pm](https://cloud.githubusercontent.com/assets/111218/14165263/037ee29c-f6bc-11e5-9e01-61fdd4fab276.png)
![screen shot 2016-03-30 at 3 39 28 pm](https://cloud.githubusercontent.com/assets/111218/14165264/05e012e0-f6bc-11e5-98d4-d19fac7693b9.png)

**Comment by jvine** [comment]
New use case for this field: Setting up a new "online" location for several libraries during COVID-19 remote instruction. The slug is sufficient to display the hours on the library website, but there's no link from the location page on library-hours back to the website. I think it's a minor use case at this level, but still inconsistent behaviour.
